version: '3.8'

services:
  paintquote-dev:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: test
    ports:
      - "3000:3000"
    environment:
      # Database
      DATABASE_PATH: /app/data/painting_quotes_app.db
      
      # Development mode
      NODE_ENV: development
      
      # Authentication
      JWT_SECRET: test-jwt-secret-key
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: test-nextauth-secret-key
      
      # AI Services (using your keys if available)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
      
      # Application
      PORT: 3000
      HOSTNAME: "0.0.0.0"
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      NEXT_PUBLIC_APP_NAME: PaintQuote Pro
      
      # Features
      NEXT_PUBLIC_ENABLE_AI_CHAT: "true"
      NEXT_PUBLIC_ENABLE_PAYMENTS: "false"
      NEXT_PUBLIC_ENABLE_EMAIL: "false"
      
      # Stripe test values
      STRIPE_SECRET_KEY: sk_test_dummy
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_dummy
      STRIPE_WEBHOOK_SECRET: whsec_dummy
      STRIPE_PROFESSIONAL_MONTHLY_PRICE_ID: price_dummy
      STRIPE_PROFESSIONAL_YEARLY_PRICE_ID: price_dummy
      
    volumes:
      # Mount source for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
      # Persist database
      - paintquote_test_data:/app/data
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: playwright
    depends_on:
      paintquote-dev:
        condition: service_healthy
    environment:
      - PLAYWRIGHT_BASE_URL=http://paintquote-dev:3000
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    command: >
      sh -c "
        echo 'Waiting for app to be ready...' &&
        sleep 10 &&
        echo 'Running Playwright tests...' &&
        npx playwright test --reporter=html,list
      "
    profiles:
      - test

volumes:
  paintquote_test_data:
    driver: local