version: '3.8'

services:
  paintquote:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      # Database
      DATABASE_PATH: /app/data/painting_quotes_app.db
      
      # Supabase (placeholder values)
      NEXT_PUBLIC_SUPABASE_URL: https://placeholder.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: placeholder_anon_key
      SUPABASE_SERVICE_ROLE_KEY: placeholder_service_key
      
      # Authentication
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      NEXTAUTH_URL: http://localhost:3001
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-nextauth-secret-key-change-in-production}
      
      # AI Services (optional)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY:-}
      
      # Application
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      NEXT_PUBLIC_APP_NAME: PaintQuote Pro
      
      # Features
      NEXT_PUBLIC_ENABLE_AI_CHAT: "true"
      NEXT_PUBLIC_ENABLE_PAYMENTS: "false"
      NEXT_PUBLIC_ENABLE_EMAIL: "false"
      
      # Stripe (placeholder values)
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_dummy}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY:-pk_test_dummy}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_dummy}
      
    volumes:
      # Persist database
      - paintquote_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  paintquote_data:
    driver: local