services:
  paintquote-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
    environment:
      # Database - Use memory adapter by not providing Supabase URLs
      DATABASE_PATH: /app/data/painting_quotes_app.db
      
      # Force production mode with memory adapter
      NODE_ENV: production
      VERCEL: "1"
      
      # Authentication
      JWT_SECRET: test-jwt-secret-change-in-production
      NEXTAUTH_URL: http://localhost:3001
      NEXTAUTH_SECRET: test-nextauth-secret-change-in-production
      
      # Application
      PORT: 3001
      HOSTNAME: "0.0.0.0"
      NEXT_PUBLIC_SITE_URL: http://localhost:3001
      NEXT_PUBLIC_APP_NAME: PaintQuote Pro
      
      # Features
      NEXT_PUBLIC_ENABLE_AI_CHAT: "true"
      NEXT_PUBLIC_ENABLE_PAYMENTS: "false"
      NEXT_PUBLIC_ENABLE_EMAIL: "false"
      
    volumes:
      # Persist database
      - paintquote_test_data:/app/data
    restart: unless-stopped

volumes:
  paintquote_test_data:
    driver: local