-- Complete fix for ALL missing columns in quotes table
-- Run this entire script in your Supabase SQL Editor

ALTER TABLE quotes 
ADD COLUMN IF NOT EXISTS doors_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS windows_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS priming_sqft INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS painting_rate DECIMAL(10,2) DEFAULT 2.50,
ADD COLUMN IF NOT EXISTS priming_rate DECIMAL(10,2) DEFAULT 0.40,
ADD COLUMN IF NOT EXISTS trim_rate DECIMAL(10,2) DEFAULT 1.92,
ADD COLUMN IF NOT EXISTS door_rate DECIMAL(10,2) DEFAULT 100.00,
ADD COLUMN IF NOT EXISTS window_rate DECIMAL(10,2) DEFAULT 25.00,
ADD COLUMN IF NOT EXISTS walls_rate DECIMAL(10,2) DEFAULT 2.50,
ADD COLUMN IF NOT EXISTS ceilings_rate DECIMAL(10,2) DEFAULT 2.50,
ADD COLUMN IF NOT EXISTS walls_paint_cost DECIMAL(10,2) DEFAULT 26.00,
ADD COLUMN IF NOT EXISTS ceilings_paint_cost DECIMAL(10,2) DEFAULT 25.00,
ADD COLUMN IF NOT EXISTS trim_paint_cost DECIMAL(10,2) DEFAULT 35.00,
ADD COLUMN IF NOT EXISTS sundries_cost DECIMAL(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS sundries_percentage INTEGER DEFAULT 12,
ADD COLUMN IF NOT EXISTS labor_percentage INTEGER DEFAULT 30,
ADD COLUMN IF NOT EXISTS paint_coverage INTEGER DEFAULT 350,
ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_amount DECIMAL(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS base_cost DECIMAL(12,2),
ADD COLUMN IF NOT EXISTS markup_percentage DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS room_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS confirmed_rates JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS room_data JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS conversation_summary TEXT;

-- Show all columns to verify
SELECT column_name, data_type, column_default
FROM information_schema.columns 
WHERE table_name = 'quotes' 
ORDER BY ordinal_position;